[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["pyccxt"]

[project]
name = "pyccxt"
authors = [
  { name="Holger Nahrstaedt", email="nahrstaedt@gmail.com" },
]
description = "Python lib for accessing ccxt"
keywords = ["price", "ccxt", "ticker"]
urls = { Homepage = "https://github.com/holgern/pyccxt" }
readme = "README.md"
dependencies = [
    "urllib3",
    "typer",
    "rich",
    "requests",
    "ccxt>=4.5.42",
]
license = {file = "LICENSE"}
classifiers=[
    'Intended Audience :: Developers',
    'License :: OSI Approved :: MIT License',
    'Operating System :: OS Independent',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Topic :: Software Development :: Libraries',
]

dynamic=["version"]

[tool.setuptools_scm]
write_to = "pyccxt/_version.py"

[project.scripts]
pyccxt = "pyccxt.cli:app"

[tool.tox]
legacy_tox_ini = """

[testenv]
deps =
    pytest
    pytest-cov[all]
    responses
commands =
    pytest
"""
